version: '3'

volumes:
  postgres_data: {}
  redis_data: {}

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - .:/myappa
    depends_on:
      - db
      - redis

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - web
    ports:
      - "80:80"

  redis:
    image: 'redis'
    volumes:
      - redis_data:/data

  db:
    image: postgres # postgres:9.4.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
